const data = [
    {
        'id': 1,
        'name': 'Bonnie McMurray',
        'email': 'bonnie@hotmail.com',
        'age': 25,
        'occupation': 'Bartender',
        'numOfCats': 2, 
        'avgDailyWaterConsumptionLiters': 1,
        'location': 'Canada',
        'phoneNumber': '301-555-1212',
        'favColor': 'Pink',
        'bestInLife': 'Flowers',
    },
    {
        'id': 2,
        'name': 'Katy',
        'email': 'katykat@hotmail.com',
        'age': 25,
        'occupation': 'Farmer',
        'numOfCats': 1, 
        'avgDailyWaterConsumptionLiters': 2,
        'location': 'Canada',
        'phoneNumber': '301-555-1212',
        'favColor': 'Red',
        'bestInLife': 'Dancing',
    },
    {
        'id': 3,
        'name': 'Wayne',
        'email': 'wayne@yahoo.com',
        'age': 30,
        'occupation': 'Farmer',
        'numOfCats': 0, 
        'avgDailyWaterConsumptionLiters': 4,
        'location': 'Canada',
        'phoneNumber': '301-555-1212',
        'favColor': 'Red',
        'bestInLife': 'A good fight',
    },
    {
        'id': 4,
        'name': 'Daryl',
        'email': 'darry@yahoo.com',
        'age': 30,
        'occupation': 'Farmer',
        'numOfCats': 1, 
        'avgDailyWaterConsumptionLiters': 3,
        'location': 'Canada',
        'phoneNumber': '301-555-1212',
        'favColor': 'Pink',
        'bestInLife': 'Friends',
    }
]

export default data